services:
  - type: web
    name: chat-app-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: JWT_SECRET
        value: MohcenAppSuperSecretKey
      - key: DATABASE_URL
        fromDatabase:
          name: chat_app_db
          property: connectionString

databases:
  - name: chat_app_db
    databaseName: chat_app_db
    user: chat_user
    plan: free